### ISSUE TITLE
Add support for 'package @ git+ssh://git@github.com/mydep/dep.git'

### ISSUE THREAD

**Issue by sla-te** [JetBrains/requirements#72]
Create a file requirements.txt and put in `package @ git+ssh://git@github.com/mydep/dep.git`.

In any file do import package, notice the warning, that the package is not installed.

The warning goes away if we change package @ git+ssh://git@github.com/mydep/dep.git to package inside requirements.txt

**Comment by meanmail** [comment]
@sla-te  please could you create issue in https://youtrack.jetbrains.com/issues/PY? It's bug in PyCharm inspections
